name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        step: [install, test]
        optimize: [Debug, ReleaseSmall, ReleaseSafe, ReleaseFast]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig build ${{ matrix.step }} -Doptimize=${{ matrix.optimize }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check .
